// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mobwtghjbdovunfbzyvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vYnd0Z2hqYmRvdnVuZmJ6eXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTYyMTYsImV4cCI6MjA1OTY5MjIxNn0.YU8qssxrkii5ilt2pMCXoiwWfA22hDzFkwQz5EnRNMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);